language: bash

services:
  - docker

stages:
  - docker-build


jobs:
  include:
    - stage: docker-build
      script:
        - echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USER" --password-stdin
        - docker build -t "$DOCKER_USER/DockerPipelineExample" .
        - docker pull "$DOCKER_USER/DockerPipelineExample"
